services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: $PG_USER
  #     POSTGRES_PASSWORD: $PG_PASSWORD
  #     POSTGRES_DB: $PG_DB_NAME
  #   networks:
  #     - paybills-network

  paybills-api:
    # depends_on: [db]
    image : paybills-api:latest
    ports:
      - 5001:5001
    networks:
      - paybills-network
    environment:
      - TOKEN_KEY=$TOKEN_KEY
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - PG_HOST=$PG_HOST
      - PG_PORT=$PG_PORT
      - PG_USER=$PG_USER
      - PG_PASSWORD=$PG_PASSWORD
      - PG_DB=$PG_DB
      # - ASPNETCORE_HTTP_PORT=http://+:5001
      - ASPNETCORE_URLS=http://+:5001

networks:
  paybills-network:
    driver: bridge