services:
  # elasticsearch:
  #   container_name: elasticsearch
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
  #   ports:
  #     - 9200:9200
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticsearch/data
  #   environment:
  #     - xpack.monitoring.enabled=true
  #     - xpack.watcher.enabled=false
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - discovery.type=single-node
  #   networks:
  #     - paybills-network

  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:7.13.4
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
  #   environment:
  #     - ELASTICSEARCH_URL=http://localhost:9200
  #   networks:
  #     - paybills-network

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    command: >
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB
    volumes:
      - pgdata:/var/lib/postgresql/data

  paybills-api:
    depends_on: 
      - db
    image : nilsojr/paybills-api:latest
    ports:
      - "5000:5000"
    environment:
      - TOKEN_KEY=$TOKEN_KEY
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - PG_HOST=db
      - PG_USER=$PG_USER
      - PG_DB=$PG_DB
      - PG_PASSWORD=$PG_PASSWORD
      - ASPNETCORE_HTTP_PORT=http://+:5000
      - ASPNETCORE_URLS=http://+:5000

volumes:
  pgdata: