name: .NET test

on:
  workflow_dispatch:
  
jobs:
  build:   
    runs-on: ubuntu-latest
    name: build
    steps:
      - id: set-variables
        run: |
          echo "MY_VAR=value1" >> $GITHUB_ENV
          echo "MY_VAR2=value2" >> $GITHUB_OUTPUT
      - name: output values
        run: |
          echo "MY_VAR -> " $MY_VAR          
    outputs:
      MY_VAR_TWO: ${{ steps.set-variables.outputs.MY_VAR2 }}
      
  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: output values
        run: |
          echo "MY_VAR -> " $MY_VAR
          echo "MY_VAR2 -> " ${{ needs.build.outputs.MY_VAR_TWO }} 
