name: .NET deploy

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build Paybills.API\Paybills.API.csproj --no-restore -c Release --output ../../paybills-API
